<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "marketplace"
 *
 * Auto generated by Extension Builder 2016-04-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Marketplace',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Joe Schäfer',
	'author_email' => 'joe@schaefer-webentwicklung.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.14.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'ws_scss' => '1.1.1-1.99.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
